// client/src/ProductData.jsx

const productsTop = [
  {
    name: 'Regular Fit Solid Cotton Shirt',
    price: 1350,
    sku: 'REG1350M',
    stock: 3,
    type: 'mens',
    category: 'T-Shirts',
    image: 'regfit1.png',
    description: 'This shirt offers a crisp, tailored fit in breathable cotton, ideal for daily wear and semi-formal occasions.',
    details: ['100% Cotton', 'Regular fit', 'Button-down collar', 'Machine washable'],
    care: ['Wash at max 40°C', 'Do not bleach', 'Tumble dry low', 'Iron at medium temperature'],
  },
  {
    name: 'Custom Slim Fit Mesh Polo Shirt',
    price: 1325,
    sku: 'CSF1325M',
    stock: 5,
    type: 'mens',
    category: 'T-Shirts',
    image: 'slimfit1.png',
    description: 'A modern slim-fit polo made with breathable mesh fabric and a ribbed collar for all-day style.',
    details: ['Mesh cotton blend', 'Slim fit cut', 'Ribbed collar and cuffs', 'Two-button placket'],
    care: ['Wash cold', 'Do not bleach', 'Line dry', 'Cool iron if needed'],
  },
  {
    name: 'Custom Slim Fit Jersey Crewneck T-Shirt',
    price: 1295,
    sku: 'CSF1295M',
    stock: 7,
    type: 'mens',
    category: 'T-Shirts',
    image: 'slimfit2.png',
    description: 'Made from soft jersey cotton, this slim-fit crewneck tee is perfect for layering or wearing solo.',
    details: ['Slim fit', 'Crewneck', 'Lightweight jersey', 'Short sleeves'],
    care: ['Machine wash warm', 'Do not bleach', 'Tumble dry low'],
  },
  {
    name: 'Untucked Oxford Shirt',
    price: 1800,
    sku: 'OXF1800M',
    stock: 2,
    type: 'mens',
    category: 'Jackets',
    image: 'oxford1.png',
    description: 'A relaxed-fit Oxford shirt designed to be worn untucked, combining ease and elegance.',
    details: ['Oxford cotton', 'Rounded hem', 'Chest pocket', 'Button-down'],
    care: ['Cold wash', 'Do not bleach', 'Iron medium'],
  },
  {
    name: 'Paris Polo Shirt Regular Fit Stretch',
    price: 1950,
    sku: 'PPS1950M',
    stock: 4,
    type: 'mens',
    category: 'T-Shirts',
    image: 'regfit2.png',
    description: 'This Paris Polo combines timeless style with stretch fabric for extra comfort in a regular fit.',
    details: ['Stretch cotton blend', 'Regular fit', 'Embroidered logo', 'Flat knit collar'],
    care: ['Delicate wash 30°C', 'Do not bleach', 'Dry flat'],
  },
  {
    name: 'Custom Slim Fit Soft Cotton Polo Shirt',
    price: 1950,
    sku: 'CSSC1950M',
    stock: 6,
    type: 'mens',
    category: 'T-Shirts',
    image: 'slimfit3.png',
    description: 'Designed in a soft-touch cotton fabric, this slim polo brings both class and comfort.',
    details: ['Slim fit', 'Soft cotton material', 'Short sleeves', 'Three-button placket'],
    care: ['Gentle wash', 'No bleach', 'Cool tumble dry'],
  },
];

const productsBottom = [
  {
    name: 'Breathable Jersey Tennis Socks',
    price: 750,
    sku: 'BJT750W',
    stock: 8,
    type: 'womens',
    category: 'Footwear',
    image: 'jsocks1.png',
    description: 'Stay cool and dry during play with these lightweight and breathable tennis socks.',
    details: ['Breathable cotton', 'Low-cut athletic design', 'Elastic arch support'],
    care: ['Wash with like colors', 'Avoid fabric softener', 'Air dry'],
  },
  {
    name: 'Striped Ribbed Sock',
    price: 450,
    sku: 'SRS450W',
    stock: 5,
    type: 'womens',
    category: 'Accessories',
    image: 'ribsock1.png',
    description: 'A colorful striped sock with ribbed texture for a snug and fashionable fit.',
    details: ['Ribbed knit cotton blend', 'Stripe pattern', 'Reinforced toe and heel'],
    care: ['Wash inside out', 'Do not bleach', 'Hang dry'],
  },
  {
    name: 'Corgi Dog Socks Khaki',
    price: 450,
    sku: 'CDSK450W',
    stock: 3,
    type: 'womens',
    category: 'Accessories',
    image: 'dogsock1.png',
    description: 'Fun and cute corgi pattern socks in khaki for the dog lover in your life.',
    details: ['Khaki base', 'Corgi print', 'Elastic top band'],
    care: ['Delicate cycle only', 'No bleach', 'Line dry only'],
  },
  {
    name: 'Pug Dog Sock Green',
    price: 450,
    sku: 'PDSG450W',
    stock: 4,
    type: 'womens',
    category: 'Accessories',
    image: 'dogsock2.png',
    description: 'Green socks with charming pug prints, adding personality and fun to any look.',
    details: ['Pug pattern', 'Soft and stretchy', 'Green base'],
    care: ['Do not bleach', 'Do not tumble dry', 'Iron on low heat'],
  },
  {
    name: '2-Pack Sport Socks',
    price: 750,
    sku: '2PSS750W',
    stock: 1,
    type: 'womens',
    category: 'Footwear',
    image: 'sportsocks1.png',
    description: 'These Sport Socks are made from organic cotton jersey and feature an ankle-length design.',
    details: [
      'Organic cotton jersey',
      'Ankle length',
      'Embroidered crocodile on side',
      'Material: Cotton (90%), Polyamide (9%), Elastane (1%)',
    ],
    care: [
      'Normal Process T Max 30',
      'Do Not Bleach',
      'Do Not Tumble Dry',
      'Iron Max Sole-Plate T 150',
      'Do Not Dry-Clean',
      'Line Dry',
    ],
  },
];

const allProducts = [...productsTop, ...productsBottom];

export { productsTop, productsBottom, allProducts };
